### ISSUE TITLE
Time stamp, "alt+left“ is invalid.

### ISSUE THREAD

**Issue by dreamsuifeng** [jsonreeder/vscode-org-mode#62] opened 2017-04-11 10:45 UTC
VSCode Version: 1.11.1
Org Mode Version: 0.1.1
"alt+right" is valid, but "alt+left" is invalid. It's a bug or my setting is wrong?

**Comment by ajtoo** [comment] 2017-04-11 17:02
Can you describe how to replicate this bug? It appears to work on our end. If you can send us some information we'd be more than happy to take a look at it.

**Comment by PGilbertSchmitt** [comment] 2017-04-11 20:08
What operating system are you running?

**Comment by dreamsuifeng** [comment] 2017-04-12 07:08
windows 10

**Comment by PGilbertSchmitt** [comment] 2017-04-12 18:09
Running this in Windows 10, and I'm unable to reproduce the problem on a fresh install of VSCode. Both `alt-left` and `alt-right`, as well as their respective commands, are working just fine on the latest version.

**Comment by erlais** [comment] 2017-04-13 08:33
for me alt+left and alt+right work with TODO items, but when in timestamp, alt+left does nothing and alt+right goes 2 days forward.

VSCode 1.12 insider
Org Mode 0.1.1

Extensions installed: Material Icon Theme, Org Mode, Project Manager, Python, Settings Sync, TortoiseSVN
Windows 10, system locale/region settings et_ee (Estonian)

**Comment by PGilbertSchmitt** [comment] 2017-04-13 13:54
Now that's some good intel. Give me a day, I'll have this fixed pronto.

**Comment by PGilbertSchmitt** [comment] 2017-04-13 20:01
Regrettably, I'm having an issue in which I'm not getting the issue. I can't seem to replicate this on any of my Windows machines, yet at the same time, I'm pretty sure I know where the offending code. I can no longer promise that this will be fixed today, but hopefully we can recreate the error on our end.

**Comment by erlais** [comment] 2017-04-13 20:11
No worries. I played around with locale settings in my system but no dice. I have the same issue with my laptop and desktop computers and the laptop was very recent fresh install of VSCode and just ran sync settings on it...

Nevertheless I just wanted to say I'm super happy that you are taking on Org mode for VSCode! Happy easter :)

**Comment by PGilbertSchmitt** [comment] 2017-04-14 20:32
The most recent update should hopefully have been patched. I couldn't actually replicate the issue because it likely has to doing with timezones, so I'll keep this issue open until you tell me that it's fixed. Please let me know as soon as you can.

**Comment by erlais** [comment] 2017-04-14 20:35
it is fixed! Thanks.

**Closed** 2017-04-16 22:50 UTC
